### PR TITLE
add bulk upsert function

### PR DESCRIPTION
**Pull request by Betula-L**

### CODE REVIEW

**Comment by bombsimon** [comment]
This looks like an awful lot of duplication. I think it would be better to create one method that takes an bulk action (`INSERT`, `INSERT IGNORE`, `INSERT ... ON DUPLICATE KEY` etc) and then just pass that query to the bulk function. By doing this there will be a lot of places to keep track of and update when needed. You can have a look at [this implementation](https://github.com/bombsimon/gorm-bulk/blob/master/gorm_bulk.go#L13-L26) as a reference. 

<sub>_Sorry for shameless self promotion, although not saying you should switch library, just linking as an example._</sub>

**Review by bombsimon — CHANGES_REQUESTED** [review]
I don't think this is a good way forward for this library, I would rather see keeping the signature but restructuring the code in a way that each query type uses the same code to generate columns and values.

**Comment by bombsimon** [comment]
Also, don't spend too much time on this, according to https://github.com/jinzhu/gorm/issues/255#issuecomment-590287329 this bulk feature will be featured in Gorm v2 which will be released soon.

**Comment by Betula-L** [comment]
OK. Thanks.

**Comment by bombsimon** [comment]
@Betula-L Didn't mean you should close this! The hint about the coming feature was just so you don't feel you spend unnecessary time but I'll gladly accept the feature in this project!

I think the feature you added is great, I just thing a different approach would be better to improve maintainability and keep it more [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself).

Please feel free to reopen this issue and I'll gladly help you out with tips and/or ideas!

**Pull request closed without merging**
