### PR TITLE
Add test to ensure following naming strategy and column tags

### PR DESCRIPTION
**Pull request by bombsimon**
Use sqlmock to ensure that the final SQL actually has column names that
follows both the naming strategy for gorm but also the field tags. This
tests can also be used as an example of how to customize column names.

### CODE REVIEW

**Comment by bombsimon** [comment]
This test was created to adress the discussion in #29

**Comment by bombsimon** [comment]
@t-tiger After looking into how gorm does this I want to remove `ToColumnName()`. This will then resolve #29 

Please let me know if I can merge and create a new release. Technically this would require a bump to v2.0.0 to follow semver since this is breaking changes in a non backwards compatible manner. Although I guess it's possible to not follow semver strictly.

**Review by t-tiger — APPROVED** [review]
Everything is fine!

Thank you so much for being so polite to #29.
And I'm grateful for restructuring the go.mod.

**Comment by t-tiger** [comment]
> Please let me know if I can merge and create a new release. Technically this would require a bump to v2.0.0 to follow semver since this is breaking changes in a non backwards compatible manner.

Let's follow semver and set v2.0.0 to make it easier for users to understand the intent.
It would be great if you could tag it when you merge.

**Pull request merged**
